### ISSUE TITLE
I. Hate. Poor. Performance. Maybe have an option for a none-pretty sort? 

### ISSUE THREAD

**Issue by MMorsell** [alevarn/json-parser#1]
@alevarn
https://github.com/alevarn/json-parser/blob/ffef66c6ade70b15ccea023db58d060ff62fae97/src/JsonDocument.cpp#L200-L201

**Comment by alevarn** [comment]
I would like to store the objects based on the insertion order so that no sort is necessary at all.
To do that I need to figure out a clever datastructure that works like a hashtable but maintains the insertion order.

I agree performance is important =)

**Comment by MMorsell** [comment]
> I would like to store the objects based on the insertion order so that no sort is necessary at all.
> To do that I need to figure out a clever datastructure that works like a hashtable but maintains the insertion order.
> 
> I agree performance is important =)

Sounds reasonable. Good work!
